# hypr-preferences.sh - Prompt for machine-specific Hyprland preferences
#
# Usage: source this file, then call pwcca_configure_hypr_preferences.

pwcca__lua_quote() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

pwcca__prompt_yes_default() {
    local prompt="$1"
    local answer

    echo -ne "$prompt [Y/n]: "
    read -r answer

    [[ ! "$answer" =~ ^[Nn]$ ]]
}

pwcca__valid_kb_layout() {
    local layout="$1"

    [[ -n "$layout" ]] || return 1

    if command -v localectl >/dev/null 2>&1; then
        localectl list-x11-keymap-layouts | grep -qxF "$layout"
        return
    fi

    if [[ -f /usr/share/X11/xkb/rules/base.lst ]]; then
        awk '
            $1 == "! layout" { in_layouts = 1; next }
            $1 ~ /^!/ && in_layouts { exit }
            in_layouts && $1 == layout { found = 1; exit }
            END { exit found ? 0 : 1 }
        ' layout="$layout" /usr/share/X11/xkb/rules/base.lst
        return
    fi

    echo "warning: cannot validate keyboard layout; localectl and XKB rules are unavailable" >&2
    return 0
}

pwcca__prompt_kb_layout() {
    local layout

    while true; do
        echo -ne "Keyboard layout kb_layout [us]: " >&2
        read -r layout
        layout="${layout:-us}"

        if pwcca__valid_kb_layout "$layout"; then
            printf '%s\n' "$layout"
            return 0
        fi

        echo "Invalid keyboard layout '$layout'. Check available values with: localectl list-x11-keymap-layouts" >&2
    done
}

pwcca_configure_hypr_preferences() {
    local hypr_config_dir="${1:-$HOME/.config/hypr}"
    local hypr_local_dir="$hypr_config_dir/local"
    local preferences_file="$hypr_local_dir/preferences.lua"

    local swap_alt_win=true
    local solo_fullscreen=true
    local kb_layout

    echo ""
    echo -e "\e[1;34m:: Configuring Hyprland preferences...\e[0m"

    if pwcca__prompt_yes_default "Swap Alt and Win keys?"; then
        swap_alt_win=true
    else
        swap_alt_win=false
    fi

    kb_layout="$(pwcca__prompt_kb_layout)"

    if pwcca__prompt_yes_default "Enable solo-window fullscreen?"; then
        solo_fullscreen=true
    else
        solo_fullscreen=false
    fi

    mkdir -p "$hypr_local_dir"

    cat >"$preferences_file" <<EOF
-- Machine-specific Hyprland preferences.
-- Generated by install.sh / pwcca update.

return {
    swap_alt_win = $swap_alt_win,
    kb_layout = "$(pwcca__lua_quote "$kb_layout")",
    solo_fullscreen = $solo_fullscreen,
}
EOF

    echo "   -> Wrote $preferences_file"
}
