#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    repeat_delay = 200
    kb_model =
    kb_options =
    kb_rules =

    accel_profile = flat

    follow_mouse = 1

    sensitivity = -0.6 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.5
    }
}

device {
    name = bltp7853:00-347d:7853-touchpad
    accel_profile = flat
    sensitivity = 10
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 4, horizontal, workspace

# cursor {
#     no_hardware_cursors = false
# }
